SELECT name, birthdate
FROM MOVIESTAR
WHERE name NOT LIKE '%a' AND (SELECT COUNT(*) FROM MOVIE
								INNER JOIN STARSIN ON TITLE = MOVIETITLE
								WHERE STARNAME = name AND INCOLOR = 'y') > 0 AND 
									(SELECT COUNT(*) FROM MOVIE
										INNER JOIN STARSIN ON TITLE = MOVIETITLE
										WHERE STARNAME = name AND INCOLOR = 'n') > 0
ORDER BY BIRTHDATE, NAME

SELECT name, YEAR(birthdate), COUNT(studioname)
FROM MOVIESTAR
LEFT OUTER JOIN STARSIN ON name = STARNAME
LEFT OUTER JOIN Movie ON TITLE = MOVIETITLE
WHERE (SELECT COUNT(*) FROM Movie INNER JOIN STARSIN ON title = MOVIETITLE
		WHERE starname = name) <= 5
GROUP BY name, YEAR(birthdate)

SELECT c.COUNTRY, sinks FROM CLASSES c
LEFT OUTER JOIN SHIPS ON c.CLASS = SHIPS.CLASS
LEFT OUTER JOIN	(SELECT COUNTRY, COUNT(RESULT) as sinks FROM SHIPS
				INNER JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
				INNER JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
				WHERE RESULT = 'sunk'
				GROUP BY COUNTRY, RESULT) as a ON c.COUNTRY = a.COUNTRY
GROUP BY c.COUNTRY, sinks
HAVING COUNT(*) <= 3
