SELECT name, birthdate
FROM MOVIESTAR
WHERE name NOT LIKE '%a' AND (SELECT COUNT(*) FROM MOVIE
								INNER JOIN STARSIN ON TITLE = MOVIETITLE
								WHERE STARNAME = name AND INCOLOR = 'y') > 0 AND 
									(SELECT COUNT(*) FROM MOVIE
										INNER JOIN STARSIN ON TITLE = MOVIETITLE
										WHERE STARNAME = name AND INCOLOR = 'n') > 0
ORDER BY BIRTHDATE, NAME
